[package]
name = "gh-actions-test"
version = "0.1.0"
authors = ["jack <jack@signal.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
